### ISSUE TITLE
.DS_Storeはリポジトリに含めないようにしましょう

### ISSUE THREAD

**Issue by m4kvn** [miraikeitai2017/iOS-Study#4]
`.DS_Store` はリポジトリに含めないようにします。理由は、`.DS_Store` は個人のmacOS特有のファイルで他の人には必要ないからです。また、リモートにプッシュする際やローカルにクローンする際に無駄な通信量が発生したり、リポジトリ肥大化に繋がります。

この解決方法として、`.gitignore` を使用する方法があります。ただ、`.DS_Store` をリポジトリに含めないのはこのリポジトリに限ったことではないので、`.gitignore_global` を使用したりします。

詳しいことは、調べながらやってみてください。

一応参考URLを貼っておきます。
http://qiita.com/elzup/items/4c92a2abdab56db3fb4e

**Comment by YTakahashii** [comment]
`.gitignore_global`を作成することで解決しました！
`.gitignore_global`を設定した手順はこのサイトを参考にしました。
- グローバルに.gitignoreを設定する方法
  - http://vdeep.net/gitignore-global

**Comment by m4kvn** [comment]
見た感じ問題が解決してるように見えたので、このissueをCloseします
